### ISSUE TITLE
بخش ساخت حساب کاربری و ثبت نام

### ISSUE THREAD

**Issue by atcodev** [hadi-teacherlove/sg-1c48eb67#2]

**Comment by atcodev** [comment]
- شماره موبایل در ساخت حساب کاربری به سمت راست بره 
- وقتی ایمیل را اشتباه میزنی ارور نمیده لطفا فیلد تکست به ایمیل تبدیل بشه
- ارور ها یکم واضح تر نشون بده که مشکل چیه الان خیلی کلی میگه
- ارور های رمز عبور و شماره موبایل وقتی وارد نکردیم یکی باشد (رمز عبور الزامی است، شماره موبایل الزامی است)
- نمیدونم چرا شماره موبایل 09051721922 قبول نمیکنه انگار نمیشناسه این شماره هایی که بعد ۹ صفر دارن
- در زیر رمز عبور بگه که ۸ رقمی باشه که نتونن یک رقمی بزنن و ارور بده
- کد تایید ارسال نمیشه برای ثبت نام و خطا میده
- هر دفعه برای ثبت نام کد تایید بخواد (در حال حاضر یکی اگر یک مرحله جلو بره و داخل سیستم ثبت بشه دیگه نمیخواد)

**Comment by hadi-teacherlove** [comment]
1. fixed
2. fixed
3. .. 
4. ... require sms
5. fixed
6. fixed
7. .... require sms
8. fixed
9. ... require sms
10. ...
11. ...
12. ...
13. fixed
14. fixed
